<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Collection Report</title>
    <style>
        body { font-family: 'kalpurush', sans-serif; font-size: 13px; color: #333; }
        
        /* --- HEADER STYLES --- */
        .header { text-align: center; margin-bottom: 25px; border-bottom: 2px solid #2c3e50; padding-bottom: 15px; }
        .logo { height: 70px; margin-bottom: 8px; }
        .school-name-bn { font-size: 28px; font-weight: bold; color: #000; margin: 0; }
        .address-bn { font-size: 16px; color: #000; margin: 5px 0; }
        .contact-info { font-size: 14px; color: #000; margin: 5px 0; }
        
        .report-title { font-size: 18px; font-weight: bold; color: #16a085; margin: 15px 0 0 0; text-transform: uppercase; }
        .date { font-size: 12px; color: #7f8c8d; margin-top: 3px; }
        
        /* --- TABLE STYLES --- */
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 8px; border: 1px solid #bdc3c7; text-align: left; font-size: 13px; }
        th { background-color: #f9f9f9; font-weight: bold; color: #2c3e50; }
        .text-right { text-align: right; }
        
        .summary-box { width: 35%; float: right; margin-top: 30px; border: 2px solid #27ae60; border-collapse: collapse; }
        .summary-box td { padding: 10px; font-size: 15px; border: 1px solid #27ae60; }
        .summary-box .label { font-weight: bold; background-color: #e8f8f5; color: #27ae60; }
        .total-amount { font-weight: bold; color: #27ae60; }
        
        .clear { clear: both; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #7f8c8d; }
        .signature-line { margin-top: 60px; width: 100%; }
        .signature-line td { border: none; text-align: center; }
        .signature-line td span { border-top: 1px solid #000; padding-top: 5px; display: inline-block; width: 200px; }
    </style>
</head>
<body>

    <div class="header">
        <img src="{{ public_path('images/logo.png') }}" alt="School Logo" class="logo">
        <p class="school-name-bn">{{ $settings->school_name_bn ?? 'হরিমোহন সরকারি উচ্চ বিদ্যালয়' }}</p>
        <p class="address-bn">{{ $settings->address_bn ?? 'নিউ মার্কেট, চাঁপাইনবাবগঞ্জ' }}</p>
        <p class="contact-info">
            মোবাইল: {{ $settings->phone ?? '01736007998' }} | ইমেইল: {{ $settings->email ?? 'harimohan@gmail.com' }}
        </p>

        <p class="report-title">Student Fee Collection Report</p>
        <p class="date">Generated On: {{ date('d F, Y, h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th width="12%">Date</th>
                <th width="15%">Receipt No.</th>
                <th width="15%">Student ID</th>
                <th width="28%">Student Name</th>
                <th width="15%">Method</th>
                <th width="15%" class="text-right">Amount (৳)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($payments as $payment)
            <tr>
                <td>{{ \Carbon\Carbon::parse($payment->payment_date)->format('d-M-Y') }}</td>
                <td>{{ $payment->receipt?->receipt_number ?? '--' }}</td>
                <td>{{ $payment->receipt?->enrollment?->user?->student_id ?? '--' }}</td>
                <td>{{ $payment->receipt?->enrollment?->user?->name ?? '--' }}</td>
                <td>{{ $payment->payment_method }}</td>
                <td class="text-right">{{ number_format($payment->amount_paid, 2) }}</td>
            </tr>
            @empty
            <tr><td colspan="6" style="text-align: center;">No collections found for this period.</td></tr>
            @endforelse
        </tbody>
    </table>

    <table class="summary-box">
        <tr>
            <td class="label">Total Collected:</td>
            <td class="text-right total-amount">৳ {{ number_format($totalCollected, 2) }}</td>
        </tr>
    </table>
    
    <div class="clear"></div>

    <table class="signature-line">
        <tr>
            <td><span>Cashier / Accountant</span></td>
            <td><span>Headmaster / Principal</span></td>
        </tr>
    </table>

    <div class="footer">
        Generated by EduSphere School Management System
    </div>

</body>
</html>